### ISSUE TITLE
Can't reach mqqt broker

### ISSUE THREAD

**Issue by wderuijter** [ualex73/dsmr-reader-docker#1]
Hoi @ualex73 . When running the docker compose example from https://hub.docker.com/r/ualex73/dsmr-reader-docker/ DSMR reader works like a charm. Only thing is it can't reach my mqtt broker. Tried `docker exec dsmr ping 192.168.1.32`

My mqqt broker's container is using the `host` network. The host's (a synology) ip address is 192.168.1.32.

I've altered the docker-compose file so the dsmr container also uses the host network. The container runs and i can ping 192.168.1.32 with `docker exec dsmr ping 192.168.1.32`. But I cant't reach the web interface at http://192.168.1.32:8888. Am I missing something?

```
version: '3'
services:
  db-dsmr:
    image: postgres
    container_name: db-dsmr
    volumes:
      - /volume1/docker/dsmr-reader/db:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - POSTGRES_USER=dsmrreader
      - POSTGRES_PASSWORD=dsmrreader
      - POSTGRES_DB=dsmrreader
    network_mode: host
  dsmr:
    container_name: dsmr
    image: ualex73/dsmr-reader-docker
    container_name: dsmr
    restart: unless-stopped
    volumes:
      - /volume1/docker/dsmr-reader/backups:/home/dsmr/app/backups
      - /dev:/dev
    environment:
      - DB_HOST=db-dsmr
      - DSMR_USER=admin
      - DSMR_EMAIL=root@localhost
      - DSMR_PASSWORD=admin
      - VIRTUAL_HOST=localhost
    ports:
      - 8888:80
    network_mode: host      
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
```
