### ISSUE TITLE
backup maken lukt niet

### ISSUE THREAD

**Issue by Thuurke** [ualex73/dsmr-reader-docker#3]
Hallo,

Ik gebruik een pi3
Ik heb de example docker-compose gebruikt
Ik heb de docker-compose.yml in /home/pi staan en dus wordt er een map dsmreader aangemaakt met de submappen db en backups. Rechten op dsmrreader map en op de backups map is:
Group = root[0]
Owner = root[0]
octal = 0755
Op de db map is het:
Group = root[0]
Owner = 999[999]
octal = 0700
Uitlezen van wifi p1-lezer op x.x.x.x met poort 23 lukt.
Backup geeft melding: Backup creation failed, please check the dsmr_backend logfile.

```
version: '3'
services:
  db-dsmr:
    image: postgres
    container_name: db-dsmr
    volumes:
      - ./dsmrreader/db:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - POSTGRES_USER=dsmrreader
      - POSTGRES_PASSWORD=dsmrreader
      - POSTGRES_DB=dsmrreader
    networks:
      - net-dsmr

  dsmr:
    container_name: dsmr
    image: ualex73/dsmr-reader-docker
    container_name: dsmr
    restart: unless-stopped
    volumes:
      - ./dsmrreader/backups:/home/dsmr/app/backups
      - /dev:/dev
    environment:
      - DB_HOST=db-dsmr
      - DSMR_USER=admin
      - DSMR_EMAIL=root@localhost
      - DSMR_PASSWORD=admin
      - VIRTUAL_HOST=localhost
      - DSMRREADER_ADMIN_USER=admin
      - DSMRREADER_ADMIN_PASSWORD=password
    ports:
      - 8888:80
#    devices:
 #     - /dev/ttyUSB0:/dev/ttyUSB0
    networks:
      - net-dsmr

networks:
  net-dsmr:
    driver: bridge
```
